
#General mod settings
[general]
	#
	#Range: 0.0 ~ 5.0
	leavesVolume = 0.0
	#
	#Range: 0.0 ~ 5.0
	tornadoWindVolume = 0.7
	#
	#Range: 0.0 ~ 5.0
	tornadoDamageVolume = 0.7
	#
	#Range: 0.0 ~ 5.0
	windyStormVolume = 0.7
	#
	#Range: 0.0 ~ 5.0
	sirenVolume = 1.0

