
[General]
	#
	# Should lava deposit minerals onto the surrounding blocks?
	shouldLavaDepositMinerals = true
	#
	# Should hot springs deposit minerals onto the surrounding blocks?
	shouldHotSpringsDepositMinerals = true
	#
	# How often minerals can generate around lava. Lower value => more often.
	#Range: > 0
	mineralGenFrequencyLava = 128
	#
	# How often minerals can generate around hot springs. Lower value => more often.
	#Range: > 0
	mineralGenFrequencyHotSpring = 64
	#
	# Toggle smoke particles released by lava? True = smokes.
	shouldLavaSmoke = true
	#
	# Toggle whether or not lava and hot springs should deposit minerals in other dimensions than the overworld? True = not limited to the overworld.
	toggleOtherDimensions = false
	#
	# Felsic rocks contain more silica compounds than mafic, thus "felsic lava" has a higher viscosity, flow speed and distance -- like honey.
	# 
	# Standard slope distance for lava is 2, whilst 4 in the Nether.
	# Slope distance for lava in felsic rocks.
	#Range: > 0
	slopeDistanceFelsic = 3
	#
	# Slope distance for lava in sedimentary rocks.
	#Range: > 0
	slopeDistanceSedimentary = 4
	#
	# Slope distance for lava in metamorphic rocks.
	#Range: > 0
	slopeDistanceMetamorphic = 4
	#
	# Slope distance for lava in intermediate rocks.
	#Range: > 0
	slopeDistanceIntermediate = 5
	#
	# Slope distance for lava in mafic rocks.
	#Range: > 0
	slopeDistanceMafic = 6
	#
	# Standard drop off for lava is 2, whilst 1 in the Nether.
	# Drop off for lava in felsic rocks.
	#Range: > 0
	dropOffFelsic = 4
	#
	# Drop off for lava in sedimentary rocks.
	#Range: > 0
	dropOffSedimentary = 3
	#
	# Drop off for lava in metamorphic rocks.
	#Range: > 0
	dropOffMetamorphic = 3
	#
	# Drop off for lava in intermediate rocks.
	#Range: > 0
	dropOffIntermediate = 2
	#
	# Drop off for lava in mafic rocks.
	#Range: > 0
	dropOffMafic = 1
	#
	# Standard tick delay for lava is 30, whilst 10 in the Nether.
	# Tick delay for lava in felsic rocks.
	#Range: > 0
	tickDelayFelsic = 40
	#
	# Tick delay for lava in sedimentary rocks.
	#Range: > 0
	tickDelaySedimentary = 25
	#
	# Tick delay for lava in metamorphic rocks.
	#Range: > 0
	tickDelayMetamorphic = 25
	#
	# Tick delay for lava in intermediate rocks.
	#Range: > 0
	tickDelayIntermediate = 10
	#
	# Tick delay for lava in mafic rocks.
	#Range: > 0
	tickDelayMafic = 5

